/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'develop' at '16-7-27 上午11:05' with Gradle 2.14
 *
 * @author develop, @date 16-7-27 上午11:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
